Repository spq/pkappa2, pull requests merged in 2024-11, with the labels that each got.

#190 pwntools: Collapse recvuntil + send into a single sendafter
  converters/pwntools.py
Labels: enhancement

#182 keep tag/mark/service labels legible by using dark text color on low contrast
  web/src/components/Navigation.vue
  web/src/components/Results.vue
  web/src/components/Stream.vue
  web/src/components/TagColorChangeDialog.vue
  web/src/components/TagDefinitionChangeDialog.vue
  web/src/components/TagDetailsDialog.vue
  web/src/components/TagNameChangeDialog.vue
  web/src/components/Tags.vue
  web/src/lib/colors.ts
Labels: enhancement, javascript

#202 Fix referencing query data conditions before they are added
  internal/index/search_data.go
  internal/index/search_test.go
Labels: bug, go

#191 Keep selected converter when going through results
  web/src/components/Results.vue
  web/src/components/Stream.vue
Labels: enhancement, javascript
